FROM node:24-alpine

ARG UID=1000
ARG GID=1000

WORKDIR /app

COPY package*.json ./
RUN npm install

COPY . .

RUN addgroup -g ${GID} app \
    && adduser -u ${UID} -G app -D app \
    && chown -R app:app /app

USER app

EXPOSE 3000
CMD ["npm", "run", "dev", "--", "--host", "0.0.0.0"]
